version: '3.8'
services:
  mongo:
    image: mongo:latest
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes: [ mongo-data:/data/db ]
    ports: [ '27017:27017' ]

  auth:
    build:
      context: .
      dockerfile: packages/auth/Dockerfile
      # target: builder 
    image: monorepo/auth:latest
    environment:
      DATABASE_URL: mongodb://mongo:27017/mydb?replicaSet=rs0&retryWrites=true&w=majority
      JWT_SECRET: your_jwt_secret
    ports: [ '3001:3000' ]
    depends_on: [ mongo ]

  event:
    build:
      context: .
      dockerfile: packages/event/Dockerfile
    image: monorepo/event:latest
    environment:
      DATABASE_URL: mongodb://mongo:27017/mydb?replicaSet=rs0&retryWrites=true&w=majority
    ports: [ '3002:3000' ]
    depends_on: [ mongo ]

  gateway:
    build:
      context: .
      dockerfile: packages/gateway/Dockerfile
    image: monorepo/gateway:latest
    environment:
      AUTH_URL: http://auth:3000
      EVENT_URL: http://event:3000
      JWT_SECRET: your_jwt_secret
    ports: [ '3000:3000' ]
    depends_on: [ auth, event ]

volumes:
  mongo-data: